version: '3.8'
services:
  app:
    build:
      context: .
    image: whoatemyapplepie/ubuntu:22.04-nodejs18
    volumes:
      - ./volume/:/app/host-share/
    ports:
      - 8081:80
      - 3000:3000
      - 443:443
    tty: true
    command: /bin/bash